name: Publish main branch

on:
  push:
    branches:
      - main


permissions:
  id-token: write  # Required for OIDC https://docs.npmjs.com/trusted-publishers
  contents: write      # нужно для пуша

jobs:
  publish-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      # Ensure npm 11.5.1 or later is installed 
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - name: Bump version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npm version patch --force
      - name: Publish to NPM
        run: npm publish --access public
      - name: Commit and push
        run: |
          git push
